// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: UI_SMCA

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageLogoUner = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImageLogoUner, &ui_img_1999419651);
    lv_obj_set_width(ui_ImageLogoUner, LV_SIZE_CONTENT);   /// 450
    lv_obj_set_height(ui_ImageLogoUner, LV_SIZE_CONTENT);    /// 76
    lv_obj_set_x(ui_ImageLogoUner, 9);
    lv_obj_set_y(ui_ImageLogoUner, -180);
    lv_obj_set_align(ui_ImageLogoUner, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLogoUner, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLogoUner, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelTemperatura = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelTemperatura, 148);
    lv_obj_set_height(ui_PanelTemperatura, 141);
    lv_obj_set_x(ui_PanelTemperatura, -314);
    lv_obj_set_y(ui_PanelTemperatura, 14);
    lv_obj_set_align(ui_PanelTemperatura, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelTemperatura, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelTemperatura, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTemperatura, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTemperatura = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelTemperatura, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemperatura, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemperatura, -314);
    lv_obj_set_y(ui_LabelTemperatura, -37);
    lv_obj_set_align(ui_LabelTemperatura, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemperatura, "Temperatura");

    ui_LabelTemperatura1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelTemperatura1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemperatura1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemperatura1, -316);
    lv_obj_set_y(ui_LabelTemperatura1, 28);
    lv_obj_set_align(ui_LabelTemperatura1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemperatura1, "0 C");
    lv_obj_set_style_text_font(ui_LabelTemperatura1, &ui_font_bigFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelHumedad = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelHumedad, 148);
    lv_obj_set_height(ui_PanelHumedad, 141);
    lv_obj_set_x(ui_PanelHumedad, -158);
    lv_obj_set_y(ui_PanelHumedad, 14);
    lv_obj_set_align(ui_PanelHumedad, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelHumedad, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelHumedad = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelHumedad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHumedad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHumedad, -157);
    lv_obj_set_y(ui_LabelHumedad, -37);
    lv_obj_set_align(ui_LabelHumedad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHumedad, "Humedad");

    ui_ValueHumi = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ValueHumi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValueHumi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ValueHumi, -157);
    lv_obj_set_y(ui_ValueHumi, 28);
    lv_obj_set_align(ui_ValueHumi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValueHumi, "0%");
    lv_obj_set_style_text_font(ui_ValueHumi, &ui_font_bigFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPesoMerma = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelPesoMerma, 148);
    lv_obj_set_height(ui_PanelPesoMerma, 141);
    lv_obj_set_x(ui_PanelPesoMerma, -1);
    lv_obj_set_y(ui_PanelPesoMerma, 13);
    lv_obj_set_align(ui_PanelPesoMerma, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPesoMerma, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPeso = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelPeso, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPeso, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPeso, -2);
    lv_obj_set_y(ui_LabelPeso, -39);
    lv_obj_set_align(ui_LabelPeso, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPeso, "Peso");

    ui_ValuePeso = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ValuePeso, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValuePeso, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ValuePeso, 0);
    lv_obj_set_y(ui_ValuePeso, -11);
    lv_obj_set_align(ui_ValuePeso, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValuePeso, "0g");
    lv_obj_set_style_text_font(ui_ValuePeso, &ui_font_bigFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMerma = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelMerma, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMerma, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMerma, -2);
    lv_obj_set_y(ui_LabelMerma, 26);
    lv_obj_set_align(ui_LabelMerma, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMerma, "Merma");

    ui_ValueMerma = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ValueMerma, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValueMerma, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ValueMerma, 0);
    lv_obj_set_y(ui_ValueMerma, 54);
    lv_obj_set_align(ui_ValueMerma, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValueMerma, "0%");
    lv_obj_set_style_text_font(ui_ValueMerma, &ui_font_bigFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelVelAire = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelVelAire, 148);
    lv_obj_set_height(ui_PanelVelAire, 141);
    lv_obj_set_x(ui_PanelVelAire, 156);
    lv_obj_set_y(ui_PanelVelAire, 13);
    lv_obj_set_align(ui_PanelVelAire, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelVelAire, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelVelAire = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelVelAire, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVelAire, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelVelAire, 156);
    lv_obj_set_y(ui_LabelVelAire, -31);
    lv_obj_set_align(ui_LabelVelAire, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVelAire, "Velelocidad \ndel Aire");
    lv_obj_set_style_text_align(ui_LabelVelAire, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ValueVelAire = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ValueVelAire, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValueVelAire, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ValueVelAire, 156);
    lv_obj_set_y(ui_ValueVelAire, 29);
    lv_obj_set_align(ui_ValueVelAire, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValueVelAire, "0%");
    lv_obj_set_style_text_font(ui_ValueVelAire, &ui_font_midFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelEtapa = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelEtapa, 148);
    lv_obj_set_height(ui_PanelEtapa, 141);
    lv_obj_set_x(ui_PanelEtapa, 313);
    lv_obj_set_y(ui_PanelEtapa, 13);
    lv_obj_set_align(ui_PanelEtapa, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelEtapa, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelProducto = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelProducto, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelProducto, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelProducto, 314);
    lv_obj_set_y(ui_LabelProducto, -39);
    lv_obj_set_align(ui_LabelProducto, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelProducto, "Producto");
    lv_obj_set_style_text_align(ui_LabelProducto, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LabelProducto, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown2 = lv_dropdown_create(ui_Screen1);
    lv_dropdown_set_options(ui_Dropdown2, "Salame\nBondiola\nOption 3");
    lv_obj_set_width(ui_Dropdown2, 121);
    lv_obj_set_height(ui_Dropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown2, 313);
    lv_obj_set_y(ui_Dropdown2, 27);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -2);
    lv_obj_set_y(ui_Label2, -99);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Laboratorio de Industrias Carnicas");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_midFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 96);
    lv_obj_set_x(ui_Button2, -340);
    lv_obj_set_y(ui_Button2, 183);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button2, &ui_img_setting_5720427_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button2, lv_color_hex(0x252323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 141);
    lv_obj_set_height(ui_Button1, 75);
    lv_obj_set_x(ui_Button1, 0);
    lv_obj_set_y(ui_Button1, 160);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);

    ui_LabelSTARTSTOP = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelSTARTSTOP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSTARTSTOP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSTARTSTOP, 0);
    lv_obj_set_y(ui_LabelSTARTSTOP, 160);
    lv_obj_set_align(ui_LabelSTARTSTOP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSTARTSTOP, "START");
    lv_obj_set_style_text_color(ui_LabelSTARTSTOP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSTARTSTOP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
