// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: UI_SMCA

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button3 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 90);
    lv_obj_set_x(ui_Button3, -343);
    lv_obj_set_y(ui_Button3, 189);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button3, &ui_img_1859217858, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTituloScreen2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LabelTituloScreen2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTituloScreen2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTituloScreen2, 0);
    lv_obj_set_y(ui_LabelTituloScreen2, -199);
    lv_obj_set_align(ui_LabelTituloScreen2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTituloScreen2, "Seteo de variables de control");
    lv_obj_set_style_text_font(ui_LabelTituloScreen2, &ui_font_midFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSetTemperatura = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_PanelSetTemperatura, 170);
    lv_obj_set_height(ui_PanelSetTemperatura, 170);
    lv_obj_set_x(ui_PanelSetTemperatura, -300);
    lv_obj_set_y(ui_PanelSetTemperatura, 0);
    lv_obj_set_align(ui_PanelSetTemperatura, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSetTemperatura, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -300);
    lv_obj_set_y(ui_Label3, -65);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Temperatura");

    ui_SetTemperatura = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_SetTemperatura, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetTemperatura, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetTemperatura, -300);
    lv_obj_set_y(ui_SetTemperatura, -10);
    lv_obj_set_align(ui_SetTemperatura, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetTemperatura, "20 C");
    lv_obj_set_style_text_font(ui_SetTemperatura, &ui_font_bigFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSetMasTemp = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonSetMasTemp, 60);
    lv_obj_set_height(ui_ButtonSetMasTemp, 50);
    lv_obj_set_x(ui_ButtonSetMasTemp, -260);
    lv_obj_set_y(ui_ButtonSetMasTemp, 50);
    lv_obj_set_align(ui_ButtonSetMasTemp, LV_ALIGN_CENTER);

    ui_LabelSetMasTemp = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LabelSetMasTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSetMasTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSetMasTemp, -260);
    lv_obj_set_y(ui_LabelSetMasTemp, 48);
    lv_obj_set_align(ui_LabelSetMasTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSetMasTemp, "+");
    lv_obj_set_style_text_font(ui_LabelSetMasTemp, &ui_font_midFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSetMenosTemp = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonSetMenosTemp, 60);
    lv_obj_set_height(ui_ButtonSetMenosTemp, 50);
    lv_obj_set_x(ui_ButtonSetMenosTemp, -340);
    lv_obj_set_y(ui_ButtonSetMenosTemp, 50);
    lv_obj_set_align(ui_ButtonSetMenosTemp, LV_ALIGN_CENTER);

    ui_LabelSetMenosTemp = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LabelSetMenosTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSetMenosTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSetMenosTemp, -340);
    lv_obj_set_y(ui_LabelSetMenosTemp, 47);
    lv_obj_set_align(ui_LabelSetMenosTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSetMenosTemp, "-");
    lv_obj_set_style_text_font(ui_LabelSetMenosTemp, &ui_font_midFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSetHumedad = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_PanelSetHumedad, 170);
    lv_obj_set_height(ui_PanelSetHumedad, 170);
    lv_obj_set_x(ui_PanelSetHumedad, -100);
    lv_obj_set_y(ui_PanelSetHumedad, 0);
    lv_obj_set_align(ui_PanelSetHumedad, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSetHumedad, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -100);
    lv_obj_set_y(ui_Label4, -65);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Humedad");

    ui_SetHumedad = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_SetHumedad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetHumedad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetHumedad, -100);
    lv_obj_set_y(ui_SetHumedad, -10);
    lv_obj_set_align(ui_SetHumedad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetHumedad, "80 %");
    lv_obj_set_style_text_font(ui_SetHumedad, &ui_font_bigFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSetMenosHum = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonSetMenosHum, 60);
    lv_obj_set_height(ui_ButtonSetMenosHum, 50);
    lv_obj_set_x(ui_ButtonSetMenosHum, -140);
    lv_obj_set_y(ui_ButtonSetMenosHum, 50);
    lv_obj_set_align(ui_ButtonSetMenosHum, LV_ALIGN_CENTER);

    ui_LabelSetMenosHum = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LabelSetMenosHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSetMenosHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSetMenosHum, -140);
    lv_obj_set_y(ui_LabelSetMenosHum, 47);
    lv_obj_set_align(ui_LabelSetMenosHum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSetMenosHum, "-");
    lv_obj_set_style_text_font(ui_LabelSetMenosHum, &ui_font_midFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSetMasHum = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonSetMasHum, 60);
    lv_obj_set_height(ui_ButtonSetMasHum, 50);
    lv_obj_set_x(ui_ButtonSetMasHum, -60);
    lv_obj_set_y(ui_ButtonSetMasHum, 50);
    lv_obj_set_align(ui_ButtonSetMasHum, LV_ALIGN_CENTER);

    ui_LabelSetMasHum = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LabelSetMasHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSetMasHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSetMasHum, -60);
    lv_obj_set_y(ui_LabelSetMasHum, 48);
    lv_obj_set_align(ui_LabelSetMasHum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSetMasHum, "+");
    lv_obj_set_style_text_font(ui_LabelSetMasHum, &ui_font_midFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSetMerma = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_PanelSetMerma, 170);
    lv_obj_set_height(ui_PanelSetMerma, 170);
    lv_obj_set_x(ui_PanelSetMerma, 100);
    lv_obj_set_y(ui_PanelSetMerma, 0);
    lv_obj_set_align(ui_PanelSetMerma, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSetMerma, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 100);
    lv_obj_set_y(ui_Label5, -60);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Porcentaje\nMerma total");
    lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetMerma = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_SetMerma, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetMerma, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetMerma, 100);
    lv_obj_set_y(ui_SetMerma, -10);
    lv_obj_set_align(ui_SetMerma, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetMerma, "0%");
    lv_obj_set_style_text_font(ui_SetMerma, &ui_font_bigFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSetMenosMerma = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonSetMenosMerma, 60);
    lv_obj_set_height(ui_ButtonSetMenosMerma, 50);
    lv_obj_set_x(ui_ButtonSetMenosMerma, 60);
    lv_obj_set_y(ui_ButtonSetMenosMerma, 50);
    lv_obj_set_align(ui_ButtonSetMenosMerma, LV_ALIGN_CENTER);

    ui_LabelSetMenosMerma = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LabelSetMenosMerma, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSetMenosMerma, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSetMenosMerma, 60);
    lv_obj_set_y(ui_LabelSetMenosMerma, 47);
    lv_obj_set_align(ui_LabelSetMenosMerma, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSetMenosMerma, "-");
    lv_obj_set_style_text_font(ui_LabelSetMenosMerma, &ui_font_midFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSetMasMerma = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonSetMasMerma, 60);
    lv_obj_set_height(ui_ButtonSetMasMerma, 50);
    lv_obj_set_x(ui_ButtonSetMasMerma, 140);
    lv_obj_set_y(ui_ButtonSetMasMerma, 50);
    lv_obj_set_align(ui_ButtonSetMasMerma, LV_ALIGN_CENTER);

    ui_LabelSetMasMerma = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LabelSetMasMerma, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSetMasMerma, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSetMasMerma, 140);
    lv_obj_set_y(ui_LabelSetMasMerma, 48);
    lv_obj_set_align(ui_LabelSetMasMerma, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSetMasMerma, "+");
    lv_obj_set_style_text_font(ui_LabelSetMasMerma, &ui_font_midFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSetVelAire = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_PanelSetVelAire, 170);
    lv_obj_set_height(ui_PanelSetVelAire, 170);
    lv_obj_set_x(ui_PanelSetVelAire, 300);
    lv_obj_set_y(ui_PanelSetVelAire, 0);
    lv_obj_set_align(ui_PanelSetVelAire, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSetVelAire, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 300);
    lv_obj_set_y(ui_Label6, -60);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Porcentaje \nVelocidad de aire");
    lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetVelAire = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_SetVelAire, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetVelAire, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetVelAire, 300);
    lv_obj_set_y(ui_SetVelAire, -10);
    lv_obj_set_align(ui_SetVelAire, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetVelAire, "0%");
    lv_obj_set_style_text_font(ui_SetVelAire, &ui_font_bigFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSetMenosVelAire = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonSetMenosVelAire, 60);
    lv_obj_set_height(ui_ButtonSetMenosVelAire, 50);
    lv_obj_set_x(ui_ButtonSetMenosVelAire, 260);
    lv_obj_set_y(ui_ButtonSetMenosVelAire, 50);
    lv_obj_set_align(ui_ButtonSetMenosVelAire, LV_ALIGN_CENTER);

    ui_LabelSetMenosVel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LabelSetMenosVel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSetMenosVel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSetMenosVel, 260);
    lv_obj_set_y(ui_LabelSetMenosVel, 47);
    lv_obj_set_align(ui_LabelSetMenosVel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSetMenosVel, "-");
    lv_obj_set_style_text_font(ui_LabelSetMenosVel, &ui_font_midFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSetMasVelAire = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonSetMasVelAire, 60);
    lv_obj_set_height(ui_ButtonSetMasVelAire, 50);
    lv_obj_set_x(ui_ButtonSetMasVelAire, 340);
    lv_obj_set_y(ui_ButtonSetMasVelAire, 50);
    lv_obj_set_align(ui_ButtonSetMasVelAire, LV_ALIGN_CENTER);

    ui_LabelSetMasVel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LabelSetMasVel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSetMasVel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSetMasVel, 340);
    lv_obj_set_y(ui_LabelSetMasVel, 48);
    lv_obj_set_align(ui_LabelSetMasVel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSetMasVel, "+");
    lv_obj_set_style_text_font(ui_LabelSetMasVel, &ui_font_midFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSetMasTemp, ui_event_ButtonSetMasTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSetMenosTemp, ui_event_ButtonSetMenosTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSetMenosHum, ui_event_ButtonSetMenosHum, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSetMasHum, ui_event_ButtonSetMasHum, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSetMenosMerma, ui_event_ButtonSetMenosMerma, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSetMasMerma, ui_event_ButtonSetMasMerma, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSetMenosVelAire, ui_event_ButtonSetMenosVelAire, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSetMasVelAire, ui_event_ButtonSetMasVelAire, LV_EVENT_ALL, NULL);

}
