// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: UI_SMCA

#ifndef _UI_SMCA_UI_H
#define _UI_SMCA_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_ImageLogoUner;
extern lv_obj_t * ui_PanelTemperatura;
extern lv_obj_t * ui_LabelTemperatura;
extern lv_obj_t * ui_LabelTemperatura1;
extern lv_obj_t * ui_PanelHumedad;
extern lv_obj_t * ui_LabelHumedad;
extern lv_obj_t * ui_ValueHumi;
extern lv_obj_t * ui_PanelPesoMerma;
extern lv_obj_t * ui_LabelPeso;
extern lv_obj_t * ui_ValuePeso;
extern lv_obj_t * ui_LabelMerma;
extern lv_obj_t * ui_ValueMerma;
extern lv_obj_t * ui_PanelVelAire;
extern lv_obj_t * ui_LabelVelAire;
extern lv_obj_t * ui_ValueVelAire;
extern lv_obj_t * ui_PanelEtapa;
extern lv_obj_t * ui_LabelProducto;
extern lv_obj_t * ui_Dropdown2;
extern lv_obj_t * ui_Label2;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_LabelSTARTSTOP;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_LabelTituloScreen2;
extern lv_obj_t * ui_PanelSetTemperatura;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_SetTemperatura;
void ui_event_ButtonSetMasTemp(lv_event_t * e);
extern lv_obj_t * ui_ButtonSetMasTemp;
extern lv_obj_t * ui_LabelSetMasTemp;
void ui_event_ButtonSetMenosTemp(lv_event_t * e);
extern lv_obj_t * ui_ButtonSetMenosTemp;
extern lv_obj_t * ui_LabelSetMenosTemp;
extern lv_obj_t * ui_PanelSetHumedad;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_SetHumedad;
void ui_event_ButtonSetMenosHum(lv_event_t * e);
extern lv_obj_t * ui_ButtonSetMenosHum;
extern lv_obj_t * ui_LabelSetMenosHum;
void ui_event_ButtonSetMasHum(lv_event_t * e);
extern lv_obj_t * ui_ButtonSetMasHum;
extern lv_obj_t * ui_LabelSetMasHum;
extern lv_obj_t * ui_PanelSetMerma;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_SetMerma;
void ui_event_ButtonSetMenosMerma(lv_event_t * e);
extern lv_obj_t * ui_ButtonSetMenosMerma;
extern lv_obj_t * ui_LabelSetMenosMerma;
void ui_event_ButtonSetMasMerma(lv_event_t * e);
extern lv_obj_t * ui_ButtonSetMasMerma;
extern lv_obj_t * ui_LabelSetMasMerma;
extern lv_obj_t * ui_PanelSetVelAire;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_SetVelAire;
void ui_event_ButtonSetMenosVelAire(lv_event_t * e);
extern lv_obj_t * ui_ButtonSetMenosVelAire;
extern lv_obj_t * ui_LabelSetMenosVel;
void ui_event_ButtonSetMasVelAire(lv_event_t * e);
extern lv_obj_t * ui_ButtonSetMasVelAire;
extern lv_obj_t * ui_LabelSetMasVel;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1999419651);    // assets/logo-uner.png
LV_IMG_DECLARE(ui_img_setting_5720427_png);    // assets/setting_5720427.png
LV_IMG_DECLARE(ui_img_1859217858);    // assets/log-out.png



LV_FONT_DECLARE(ui_font_bigFont);
LV_FONT_DECLARE(ui_font_midFont);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
