// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: UI_SMCA

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void statusLED(lv_event_t * e);
void BtnMasTemp(lv_event_t * e);
void BtnMenosTemp(lv_event_t * e);
void BtnMenosHum(lv_event_t * e);
void BtnMasHum(lv_event_t * e);
void BtnMenosMerma(lv_event_t * e);
void BtnMasMerma(lv_event_t * e);
void BtnMenosVel(lv_event_t * e);
void BtnMasVel(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
